COMMANDS = {
"LINE":("L","To'g'ri chiziq chizadi.","L -> Enter -> start -> end -> Enter","0,0 dan @5000<0","Devor o'qlari va konturlar","OSNAP bilan aniq nuqta tanlang."),
"PLINE":("PL","Birlashtirilgan poliliniya chizadi.","PL -> Enter -> nuqtalar -> Enter","0,0 -> 5000,0 -> 5000,3000","Devor va uchastka konturlari","Yopish uchun C ishlating."),
"XLINE":("XL","Cheksiz yordamchi chiziq chizadi.","XL -> Enter -> nuqta -> yo'nalish","0,0 dan gorizontal XLINE","O'qlar va konstruktiv yo'nalishlar","Keyin kerak bo'lsa TRIM bilan ishlang."),
"RAY":("RAY","Bir tomonga cheksiz chiziq chizadi.","RAY -> Enter -> start -> direction","0,0 dan 90 gradus","O'qlar va yordamchi chiziqlar","XLINE bilan aralashtirmang."),
"MLINE":("ML","Parallel ko'p chiziqli element chizadi.","ML -> Enter -> nuqtalar","Ikki parallel devor chizig'i","Devor tizimlari","MLSTYLE orqali ko'rinishni sozlash mumkin."),
"SPLINE":("SPL","Silliq egri chiziq yaratadi.","SPL -> Enter -> nuqtalar -> Enter","Fasadning egri konturi","Bionik va organik fasadlar","Ko'p nuqta bermang."),
"CIRCLE":("C","Aylana chizadi.","C -> Enter -> center -> radius","C -> 0,0 -> 150","Ustun va aylana elementlar","Radius yoki Diameter variantini tanlang."),
"ARC":("A","Yoy chizadi.","A -> Enter -> kerakli nuqtalar","Start -> Center -> End","Eshik ochilishi va radiusli fasad","ARC usulini command satridan tanlang."),
"ELLIPSE":("EL","Ellips chizadi.","EL -> Enter -> axis points -> other axis","6000 x 3000 ellips","Organik fasad va landshaft","Axis endpoint usuli qulay."),
"RECTANG":("REC","To'g'ri to'rtburchak chizadi.","REC -> Enter -> first point -> @width,height","@6000,4000","Xona va bino konturi","Relative coordinate ishlating."),
"POLYGON":("POL","Muntazam ko'pburchak yaratadi.","POL -> sides -> center -> radius","POL 6 -> 0,0 -> 1000","Ko'pburchak shaklli elementlar","Inscribed yoki Circumscribed tanlang."),
"DONUT":("DO","Halqa shakli yaratadi.","DO -> inner diameter -> outer diameter -> center","500 / 700 mm halqa","Aylana belgilar va dekor","Diametrlarni to'g'ri kiriting."),
"POINT":("PO","Nuqta qo'yadi.","PO -> Enter -> point","1000,2000","Geodezik va koordinata nuqtalari","PTYPE orqali ko'rinishini o'zgartiring."),
"DIVIDE":("DIV","Obyektni teng qismlarga bo'ladi.","DIV -> object -> number","Devorni 5 qismga bo'lish","Ustunlar va modul joylashuvi","Obyekt bo'linmaydi, nuqtalar qo'yiladi."),
"MEASURE":("ME","Masofa bo'yicha nuqtalar joylaydi.","ME -> object -> distance","Har 1000 mm da nuqta","Ustun va modul joylashuvi","DIV bilan farqini biling."),
"BOUNDARY":("BO","Yopiq konturdan obyekt yaratadi.","BO -> Pick Points","Xona chegarasidan polyline","Xona va maydon konturi","Kontur yopiq bo'lishi kerak."),
"REGION":("REG","Yopiq 2D obyektni region qiladi.","REG -> objects","Yopiq polylinedan region","Maydon va solid tayyorlash","Faqat mos yopiq geometriya ishlaydi."),
"WIPEOUT":("WI","Orqa obyektlarni yashiruvchi niqob yaratadi.","WI -> points","Matn orqasini tozalash","Plan belgilarida","Frame ni kerak bo'lsa OFF qiling."),
"3DPOLY":("3P","3D poliliniya yaratadi.","3P -> nuqtalar","Z qiymatli yo'l","3D model va relyef","Z koordinatalarini tekshiring."),
"HELIX":("HELIX","Spiral/heliks yaratadi.","HELIX -> center -> radius -> height","Zinapoya yoki spiral yo'l","Spiral zinapoya","Turns va Height parametrlarini tekshiring."),

"ERASE":("E","Obyektni o'chiradi.","E -> objects -> Enter","Keraksiz chiziqni o'chirish","Chizma tozalash","O'chirishdan oldin layerni tekshiring."),
"OOPS":("OOPS","Oxirgi o'chirilgan obyektni qaytaradi.","OOPS -> Enter","Tasodifan o'chirilgan devor","Chizma tiklash","UNDO bilan bir xil emas."),
"UNDO":("U","Oxirgi amalni bekor qiladi.","U -> Enter","Oxirgi OFFSET ni bekor qilish","Xatolarni qaytarish","Bir nechta amalni ham boshqarish mumkin."),
"REDO":("REDO","UNDO qilingan amalni qaytaradi.","REDO -> Enter","Bekor qilingan amalni qaytarish","Ish jarayonini tiklash","UNDO dan keyin ishlatiladi."),
"COPY":("CO","Obyekt nusxasini yaratadi.","CO -> objects -> base point -> second point","Devorni 3000 mm nusxalash","Takroriy elementlar","Multiple uchun M variantidan foydalaning."),
"MOVE":("M","Obyektni ko'chiradi.","M -> objects -> base -> destination","Eshikni 1000 mm siljitish","Plan tahriri","Base pointni aniq oling."),
"ROTATE":("RO","Obyektni aylantiradi.","RO -> object -> base point -> angle","Eshikni 90 gradus aylantirish","Eshik va fasad elementlari","Reference orqali mavjud burchakka moslang."),
"MIRROR":("MI","Oynadagi kabi aks nusxa yaratadi.","MI -> object -> mirror line","Chap derazani o'ngga akslantirish","Simmetrik plan va fasad","Source objectni o'chirish kerakligini tanlang."),
"SCALE":("SC","Obyekt o'lchamini masshtablaydi.","SC -> object -> base -> scale","1:2 yoki 2x o'lcham","Detal va chizmalar","Reference usuli aniqroq."),
"STRETCH":("S","Obyekt qismini cho'zadi.","S -> crossing window -> base -> destination","Xonani 500 mm uzaytirish","Plan o'lchamini o'zgartirish","Crossing selection ishlating."),
"LENGTHEN":("LEN","Chiziq yoki yoy uzunligini o'zgartiradi.","LEN -> option -> object","Devor uzunligini oshirish","Konturlar","Delta va Total farqini biling."),
"TRIM":("TR","Obyektni chegaraga qarab kesadi.","TR -> boundary -> object","Ortiqcha devorni kesish","Plan va fasad","2020+ versiyalarda Enter bilan barcha obyektni boundary qilish mumkin."),
"EXTEND":("EX","Obyektni chegaragacha uzaytiradi.","EX -> boundary -> object","Devorni o'qgacha uzaytirish","Plan chizmalari","TRIM ning teskarisi."),
"FILLET":("F","Ikki obyektni radius bilan birlashtiradi.","F -> R -> radius -> objects","R300 burchak","Radiusli bino va yo'l","R=0 keskin burchak hosil qiladi."),
"CHAMFER":("CHA","Ikki obyekt orasida qiya qirra yaratadi.","CHA -> D -> distances -> objects","300x300 chamfer","Fasad va detal","Distance qiymatlarini tekshiring."),
"BREAK":("BR","Obyektni ikki nuqtada uzadi.","BR -> object -> first -> second","Devorning bir qismini olib tashlash","Eshik va teshiklar","Break pointlarni OSNAP bilan oling."),
"BREAKATPOINT":("BRAT","Obyektni bitta nuqtada bo'ladi.","BRAT -> object -> point","Chiziqni bir nuqtada ajratish","Devor va o'qlar","Objectni aniq tanlang."),
"JOIN":("J","Mos obyektlarni birlashtiradi.","J -> objects -> Enter","Segmentlarni bitta polyline qilish","Konturlar","Geometriya mos bo'lishi kerak."),
"PEDIT":("PE","Polyline ni tahrirlaydi.","PE -> object -> option","LINE segmentlarini polyline qilish","Bino konturlari","Join va Width imkoniyatlari bor."),
"SPLINEDIT":("SPE","Spline ni tahrirlaydi.","SPE -> spline -> option","Egri fasadni tahrirlash","Organik arxitektura","Fit va Control Vertices usullarini sinang."),
"EXPLODE":("X","Composite obyektni qismlarga ajratadi.","X -> object","Block yoki polyline ni ajratish","Block va geometriya tahriri","Blockni explode qilish atributlarga ta'sir qilishi mumkin."),
"OFFSET":("O","Parallel nusxa yaratadi.","O -> distance -> object -> side","300 mm devor qalinligi","Devorlar va parallel chiziqlar","Architecture uchun eng ko'p ishlatiladigan commandlardan biri."),
"ARRAY":("AR","Takroriy obyektlar massivini yaratadi.","AR -> object -> type","Ustunlarni 5x4 tartibda joylash","Konstruktiv grid","Rectangular, Polar yoki Path tanlang."),
"ARRAYRECT":("AR","To'rtburchak massiv yaratadi.","ARRAYRECT -> object -> rows/columns","4x6 ustunlar","Grid va parking","Spacing qiymatlarini tekshiring."),
"ARRAYPOLAR":("AR","Aylana bo'ylab massiv yaratadi.","ARRAYPOLAR -> object -> center -> items","Aylana fasad elementlari","Radial plan","Items va angle ni belgilang."),
"ARRAYPATH":("AR","Yo'l bo'ylab takrorlaydi.","ARRAYPATH -> object -> path","Yo'l bo'ylab ustunlar","Landshaft va yo'l","Measure yoki Divide usullarini tanlash mumkin."),
"ALIGN":("AL","Obyektni boshqa geometriyaga moslaydi.","AL -> object -> source points -> destination points","Detalni fasadga moslash","Fasad va detal","Scale YES/NO variantini ehtiyot tanlang."),
"MATCHPROP":("MA","Bir obyekt xususiyatlarini boshqasiga ko'chiradi.","MA -> source -> destination","Layer va rangni moslash","Chizma standartlashtirish","Properties panelga qaraganda tezroq."),
"CHANGE":("CH","Obyektning asosiy xususiyatlarini o'zgartiradi.","CH -> object -> properties","Z qiymatini o'zgartirish","Oddiy geometriya","Ko'proq yangi workflowlarda Properties qulay."),
"SETBYLAYER":("SETBYLAYER","Obyekt xususiyatlarini ByLayer qiladi.","SETBYLAYER -> objects","Color/linetype ByLayer","Standartlashtirish","Block ichidagi obyektlar variantini tekshiring."),
"PROPERTIES":("CTRL+1","Properties oynasini ochadi.","CTRL+1 -> object","Layer, color, linetype o'zgartirish","Har qanday chizma","Object xususiyatlarini tez tekshiring."),
"QSELECT":("QSELECT","Shart bo'yicha obyektlarni tanlaydi.","QSELECT -> object type/property","Barcha TEXT obyektlarini tanlash","Katta DWG fayllar","Filter orqali ishni tezlashtiradi."),
"SELECTSIMILAR":("SELECTSIMILAR","O'xshash obyektlarni tanlaydi.","SELECTSIMILAR -> object","Barcha bir xil layerdagi obyektlar","Tozalash va standartlash","SELECTSIMILAR settings ni sozlash mumkin."),

"DIST":("DI","Ikki nuqta orasidagi masofani o'lchaydi.","DI -> first point -> second point","5000 mm xona eni","Xona va konstruksiya o'lchamlari","OSNAP bilan o'lchang."),
"AREA":("AA","Yopiq maydonni hisoblaydi.","AREA -> points/object","Xona maydoni","Eksplikatsiya va maydon hisoblari","Polyline yopiq bo'lishi shart emas, nuqtalar bilan ham ishlaydi."),
"ID":("ID","Nuqtaning koordinatasini ko'rsatadi.","ID -> point","Aks kesishmasi koordinatasi","Geodeziya va grid","UCS koordinata tizimini tekshiring."),
"LIST":("LI","Obyekt haqida texnik ma'lumot beradi.","LIST -> object","Polyline uzunligini tekshirish","Tekshiruv","Properties bilan birga ishlating."),
"MEASUREGEOM":("MEASUREGEOM","Masofa, radius, burchak va maydonni o'lchaydi.","MEASUREGEOM -> option","Distance yoki Radius","Arxitektura o'lchovlari","Bir nechta o'lchov usuli bir command ichida."),
"QUICKCALC":("QC","Ichki kalkulyatorni ochadi.","QC -> Enter","2500*3.2 hisoblash","Tezkor hisob","AutoCAD ichida oddiy hisoblar uchun qulay."),

"HATCH":("H","Yopiq maydonni shtrixlaydi.","H -> boundary -> pattern","Beton uchun ANSI31","Devor, beton, kesim","Scale va angle ni materialga moslang."),
"HATCHEDIT":("HE","Hatchni tahrirlaydi.","HE -> hatch","Pattern va scale o'zgartirish","Kesim va plan","Origin va associative holatini tekshiring."),
"GRADIENT":("—","Gradient to'ldirish yaratadi.","GRADIENT -> boundary","Ikki rangli to'ldirish","Taqdimot chizmalari","Texnik chizmada ehtiyot ishlating."),
"HATCHTOBACK":("—","Hatchni barcha obyektlarning orqasiga yuboradi.","HATCHTOBACK","Devor ustidagi hatchni orqaga yuborish","Plan grafikasi","Chizma o'qilishini yaxshilaydi."),

"LAYER":("LA","Layerlarni yaratish va boshqarish.","LA -> Enter","A-WALL, A-DOOR, A-DIMS","Professional layer standard","Layer nomlash standartini bir xil saqlang."),
"LAYISO":("LAYISO","Tanlangan layerlarni ajratib ko'rsatadi.","LAYISO -> objects","Faqat devor layerini qoldirish","Katta planlar","Lock yoki Off rejimini tanlang."),
"LAYUNISO":("LAYUNISO","LAYISO ta'sirini qaytaradi.","LAYUNISO","Barcha layerlarni qaytarish","Layer workflow","LAYISO dan keyin ishlating."),
"LAYOFF":("LAYOFF","Tanlangan layerni o'chiradi.","LAYOFF -> object","Furniture layerini yashirish","Plan tahlili","Layerni o'chiradi, obyektni emas."),
"LAYON":("LAYON","Barcha layerlarni yoqadi.","LAYON","Yashirilgan layerlarni qaytarish","Tekshiruv","Chizma ko'rinishini tiklashda foydali."),
"LAYFRZ":("LAYFRZ","Tanlangan layerni muzlatadi.","LAYFRZ -> object","Furniture layerini freeze qilish","Katta DWG","Viewport freeze bilan aralashtirmang."),
"LAYTHW":("LAYTHW","Muzlatilgan layerlarni eritadi.","LAYTHW","Barcha layerlarni thaw qilish","Layer tiklash","Katta faylda biroz vaqt olishi mumkin."),
"LAYLCK":("LAYLCK","Layerni qulflaydi.","LAYLCK -> object","Devor layerini lock qilish","Tasodifiy tahrirdan himoya","Lock belgisi paydo bo'ladi."),
"LAYULK":("LAYULK","Layer qulfini ochadi.","LAYULK -> object","A-WALL unlock","Tahrirlash","Kerakli layerni aniq tanlang."),
"LAYDEL":("LAYDEL","Layerni va undagi obyektlarni o'chiradi.","LAYDEL -> object/layer","Keraksiz layerni butunlay olib tashlash","DWG cleanup","Muhim layerni o'chirib yubormang."),
"LAYMRG":("LAYMRG","Bir layerni boshqa layerga birlashtiradi.","LAYMRG -> source -> destination","A-WALL-OLD -> A-WALL","Standartlashtirish","Old layerdagi obyektlar ko'chadi."),
"LAYMCH":("LAYMCH","Obyekt layerini boshqa layerga o'tkazadi.","LAYMCH -> object -> destination","Furniture -> A-FURN","Layer tartibi","Ko'p obyekt uchun tezkor usul."),
"LAYCUR":("LAYCUR","Obyekt layerini current layer qiladi.","LAYCUR -> object","Tanlangan A-WALL ni current qilish","Tez workflow","Layer yaratish shart emas."),
"LAYWALK":("LAYWALK","Layerlarni navbat bilan ko'rib chiqadi.","LAYWALK","Har bir layerni tekshirish","QA/QC","Katta loyihalarda juda foydali."),
"LAYERP":("LAYERP","Oldingi layer holatini qaytaradi.","LAYERP","Tasodifiy layer o'zgarishini qaytarish","Layer workflow","Oxirgi layer o'zgarishlarini tiklaydi."),

"TEXT":("DT","Bir qatorli matn yaratadi.","DT -> start -> height -> text","ROOM 101","Xona nomlari va belgilar","Standart Text Style ishlating."),
"DTEXT":("DT","Bir qatorli matn yaratadi.","DT -> Enter -> points -> text","A-01","Chizma belgilarida","TEXT bilan amalda bir xil workflow."),
"MTEXT":("MT","Ko'p qatorli matn yaratadi.","MT -> rectangle -> text","Xona tavsifi","Izoh va texnik yozuvlar","Paragraph va formatting imkoniyatlari ko'p."),
"TEXTEDIT":("—","Mavjud matnni tahrirlaydi.","TEXTEDIT -> object","ROOM 101 ni ROOM 102 qilish","Yozuvlarni tuzatish","Ikki marta bosish ham ishlaydi."),
"STYLE":("ST","Text Style boshqaradi.","STYLE -> Enter","Arial 2.5 mm style","Standart yozuvlar","Annotative style kerak bo'lishi mumkin."),
"TABLE":("TB","Jadval yaratadi.","TABLE -> rows/columns","Xona eksplikatsiyasi","Eksplikatsiya va spetsifikatsiya","Table Style bilan birga ishlating."),
"TABLESTYLE":("TS","Table Style sozlaydi.","TABLESTYLE -> Enter","Header va cell format","Spetsifikatsiya","Standart template yarating."),
"FIELD":("FIELD","Dinamik ma'lumotni matnga bog'laydi.","FIELD -> select field","Sana yoki fayl nomi","Title block","Field qiymati avtomatik yangilanadi."),
"SPELL":("SP","Matn imlosini tekshiradi.","SPELL -> objects -> Enter","Texnik yozuvlarni tekshirish","Chizma sifati","Til sozlamalarini tekshiring."),

"DIM":("DIM","Universal o'lcham yaratadi.","DIM -> points/object","5000 mm dimension","Plan va fasad","DIMSTYLE bilan standartlang."),
"DIMLINEAR":("DLI","Gorizontal yoki vertikal o'lcham beradi.","DLI -> points","Xona eni 5000","Plan o'lchamlari","Annotative dimension foydali."),
"DIMALIGNED":("DAL","Qiya obyekt bo'yicha o'lcham beradi.","DAL -> points","Diagonal devor","Qiya fasad","Haqiqiy uzunlikni beradi."),
"DIMANGULAR":("DAN","Burchakni o'lchaydi.","DAN -> objects/points","45 degree burchak","Qiya konstruksiya","Arc yoki line tanlash usuliga e'tibor bering."),
"DIMARC":("DAR","Yoy uzunligini o'lchaydi.","DAR -> arc","R2000 arc length","Radiusli fasad","Arc symbol sozlamalarini tekshiring."),
"DIMRADIUS":("DRA","Radiusni ko'rsatadi.","DRA -> arc/circle","R300","Radiusli elementlar","Leader placementni to'g'ri tanlang."),
"DIMDIAMETER":("DDI","Diametrni ko'rsatadi.","DDI -> circle","D300 ustun","Aylana ustunlar","Center mark bilan uyg'unlashtiring."),
"DIMORDINATE":("DOR","Koordinata o'lchamini beradi.","DOR -> point","X/Y grid koordinatasi","Geodezik va detal","Origin/UCS muhim."),
"DIMBASELINE":("DBA","Bir bazadan ketma-ket o'lchamlar beradi.","DBA -> existing dimension -> points","Grid o'lchamlari","Konstruktiv o'qlar","Base dimensionni avval yarating."),
"DIMCONTINUE":("DCO","Oldingi dimensiondan davom ettiradi.","DCO -> existing dimension -> points","5000 + 3000 + 4000","Plan o'lchamlari","Zanjirli dimension uchun."),
"DIMCENTER":("DCE","Aylana/yoy markazini belgilaydi.","DIMCENTER -> circle","Ustun markazi","Plan va detal","Center mark uzunligini sozlash mumkin."),
"CENTERMARK":("—","Aylana markaz belgisini yaratadi.","CENTERMARK -> circle","Ustun markazi","Texnik chizmalar","Associative holatini tekshiring."),
"CENTERLINE":("—","Ikki obyekt orasida centerline yaratadi.","CENTERLINE -> lines","Ikki parallel devor orasida o'q","Arxitektura va konstruksiya","Parallel obyektlar kerak."),
"TOLERANCE":("TOL","Geometrik tolerans belgisini yaratadi.","TOLERANCE -> Enter","Position tolerance","Konstruktiv detal","GD&T talablariga mos ishlating."),
"LEADER":("LE","Izohga ko'rsatkich chizig'i yaratadi.","LE -> points -> text","Material yozuvi","Fasad va kesim","MLeader zamonaviyroq."),
"QLEADER":("LE","Legacy leader yaratadi.","QLEADER -> points","Detalga izoh","Eski chizmalar","MLeader afzal."),
"MLEADER":("MLD","Ko'p funksiyali leader yaratadi.","MLEADER -> points -> text","Material nomi","Fasad va detal","MLeader Style ni standartlang."),
"MLEADEREDIT":("MLEADEREDIT","MLeaderni tahrirlaydi.","MLEADEREDIT -> option","Leaderni qayta joylash","Chizma izohlari","Add/Remove leader ishlatish mumkin."),

"BLOCK":("B","Block yaratadi.","B -> name -> base point -> objects","Door block yaratish","Eshik, deraza, mebel","Base pointni qulay joyga qo'ying."),
"BEDIT":("BE","Block Editorni ochadi.","BEDIT -> block","Door block geometriyasini o'zgartirish","Parametrik blocklar","O'zgarish barcha insertlarga ta'sir qiladi."),
"BSAVE":("BSAVE","Block Editor o'zgarishlarini saqlaydi.","BSAVE","Blockni saqlash","Block workflow","BEDIT ichida ishlatiladi."),
"BCLOSE":("BCLOSE","Block Editorni yopadi.","BCLOSE","Blockdan chiqish","Block workflow","Save changes variantini tekshiring."),
"INSERT":("I","Block yoki faylni joylashtiradi.","I -> block -> insertion point","Door block insert","Plan va fasad","Scale va rotationni tekshiring."),
"WBLOCK":("W","Obyekt yoki blockni alohida DWG qilib yozadi.","WBLOCK -> objects/file","Door.dwg yaratish","Kutubxona yaratish","Base pointni belgilang."),
"BURST":("BURST","Blockni atribut qiymatlarini saqlagan holda ajratadi.","BURST -> block","Title blockni tahrirlash","Atributli bloklar","Express Tools mavjudligi kerak."),
"REFEDIT":("REFEDIT","Block/Xref reference ni joyida tahrirlaydi.","REFEDIT -> reference","Xref elementini edit qilish","Xref workflow","Reference saqlashni unutmang."),

"XREF":("XR","External Reference oynasini boshqaradi.","XR -> Enter","Xref fayllarni ko'rish","Katta arxitektura loyihalari","Attach va Overlay farqini biling."),
"XATTACH":("XA","DWGni Xref sifatida biriktiradi.","XATTACH -> file","Site plan xref","Master plan","Relative path ishlatish tavsiya etiladi."),
"XCLIP":("XC","Xref yoki blockni clipping boundary bilan kesadi.","XCLIP -> reference","Faqat kerakli hududni ko'rsatish","Master plan va detail","Invert clip ham mavjud."),
"XOPEN":("—","Xref faylini alohida ochadi.","XOPEN -> reference","Xref DWGni tekshirish","Koordinatsiya","Original faylni o'zgartirishga ehtiyot bo'ling."),
"XBIND":("XB","Xrefdagi named objectlarni current DWGga bog'laydi.","XBIND -> reference","Layer yoki blockni bind qilish","Arxiv va topshirish","Fayl hajmi oshishi mumkin."),
"XCOMPARE":("—","Xref o'zgarishlarini solishtiradi.","XCOMPARE -> reference","Oldingi va yangi plan farqi","Revision nazorati","Yirik loyihalarda foydali."),

"PURGE":("PU","Ishlatilmayotgan resurslarni tozalaydi.","PU -> options","Unused layers va blocks","DWG optimallashtirish","Purge All ni ehtiyot ishlating."),
"-PURGE":("-PURGE","Command line orqali purge qiladi.","-PURGE -> options","Regapp va nested items tozalash","Batch workflow","Scriptlarda qulay."),
"OVERKILL":("OVERKILL","Takroriy va ustma-ust geometriyani tozalaydi.","OVERKILL -> objects","Ustma-ust chiziqlarni olib tashlash","DWG cleanup","Tolerance qiymatini ehtiyot sozlang."),
"AUDIT":("AUDIT","DWG xatolarini tekshiradi va tuzatadi.","AUDIT -> Y","Chizma integrity tekshiruvi","DWG diagnostikasi","Muhim fayldan oldin backup qiling."),
"RECOVER":("RECOVER","Shikastlangan DWGni tiklashga urinadi.","RECOVER -> file","Ochilmayo'tgan DWG","Favqulodda tiklash","Original fayl nusxasini saqlang."),
"RECOVERALL":("RECOVERALL","DWG va Xref fayllarini tiklashga urinadi.","RECOVERALL -> file","Xrefli buzilgan loyiha","Katta loyiha tiklash","Fayllarni backup qiling."),
"EXPORTTOAUTOCAD":("EXPORTTOAUTOCAD","Proxy/custom obyektlarni oddiy AutoCAD obyektlariga eksport qiladi.","EXPORTTOAUTOCAD","Civil/Architecture obyektlarini DWGga chiqarish","Boshqa foydalanuvchiga topshirish","Original faylni alohida saqlang."),

"ZOOM":("Z","Ko'rinishni masshtablaydi.","Z -> option","Z -> E = Extents","Katta chizmada navigatsiya","E, W, O, A variantlarini biling."),
"PAN":("P","Ko'rinishni siljitadi.","P -> drag","Plan bo'ylab yurish","Navigatsiya","Zoom bilan birga ishlating."),
"REGEN":("RE","Joriy viewni qayta hisoblaydi.","RE -> Enter","Chiziqlar noto'g'ri ko'rinsa","Display muammolari","Tez-tez ishlatish shart emas."),
"REGENALL":("REA","Barcha viewportlarni qayta hisoblaydi.","REGENALL","Layoutdagi display xatosi","Sheet va viewportlar","Katta faylda vaqt olishi mumkin."),
"REDRAW":("REDRAW","Joriy viewni qayta chizadi.","REDRAW","Display artefaktlarini tozalash","Ko'rinish","REGENdan yengilroq."),
"VPOINT":("VP","3D ko'rinish yo'nalishini belgilaydi.","VPOINT -> direction","Izometrik ko'rinish","3D model","3D navigation uchun legacy command."),
"PLAN":("PLAN","UCSga nisbatan plan ko'rinishini o'rnatadi.","PLAN -> Current UCS","Plan viewni tiklash","2D chizmalar","UCSni tekshiring."),
"UCS":("UCS","Koordinata tizimini boshqaradi.","UCS -> option","Obyekt yuzasiga UCS moslash","3D va qiya plan","World UCSga qaytish uchun W."),
"UCSICON":("UCSICON","UCS ikonkasini boshqaradi.","UCSICON -> options","Iconni origin ga qo'yish","3D koordinata","2Dda ham foydali."),
"3DORBIT":("3DO","Modelni erkin aylantirib ko'rish.","3DORBIT -> mouse","3D modelni tekshirish","3D arxitektura","Visual tekshiruv uchun."),
"VIEW":("V","Named viewlarni saqlaydi va chaqiradi.","VIEW -> New/Restore","Floor Plan view","Katta loyiha","Named views workflowni tezlashtiradi."),
"VIEWBASE":("VIEWBASE","3D modeldan 2D base view yaratadi.","VIEWBASE -> Model space","3D modeldan drawing view","Arxitektura documentation","Layout workflow bilan ishlaydi."),
"FLATSHOT":("FLATSHOT","3D modelning 2D proyeksiyasini yaratadi.","FLATSHOT -> options","Fasad yoki kesim proyeksiyasi","Documentation","Visible lines sozlamalarini tekshiring."),
"HIDE":("HIDE","Yashirin 3D obyektlarni ko'rsatmaydi.","HIDE","3D modelni soddalashtirish","3D ko'rinish","2D chizmada kam ishlatiladi."),
"SHADEMODE":("SHADEMODE","3D visual style ni o'zgartiradi.","SHADEMODE -> option","Realistic yoki Wireframe","3D tekshiruv","Visual Style bilan bog'liq."),
"VISUALSTYLES":("VS","Visual style boshqaradi.","VISUALSTYLES -> Enter","Conceptual/Realistic ko'rinish","3D arxitektura","Viewport-specific ishlatish mumkin."),

"UNITS":("UN","Chizma birliklarini sozlaydi.","UN -> Enter","Decimal, millimeters","Barcha arxitektura chizmalari","DWG boshida tekshiring."),
"LIMITS":("LIMITS","Drawing limits ni belgilaydi.","LIMITS -> points","0,0 va 42000,29700","Klassik 2D workflow","Modern AutoCADda kamroq zarur."),
"OPTIONS":("OP","AutoCAD umumiy sozlamalarini ochadi.","OP -> Enter","Display, Files, Selection","Ish muhiti","O'zgartirishdan oldin sozlamani tushuning."),
"DSETTINGS":("DS","Drafting Settings oynasini ochadi.","DS -> Enter","OSNAP, Polar, Grid","Aniq chizish","OSNAP sozlamalarini shu yerdan boshqaring."),
"OSNAP":("OS / F3","Object Snap sozlamalarini boshqaradi.","OS -> Enter","Endpoint, Midpoint, Center","Aniq geometriya","Endpoint, Midpoint, Intersection asosiylari."),
"ORTHO":("F8","Gorizontal/vertikal chizishni cheklaydi.","F8","Devorni 90 gradus chizish","2D plan","Polar bilan bir vaqtda ishlashiga e'tibor bering."),
"POLAR":("F10","Belgilangan burchaklarda tracking qiladi.","F10","30/45/90 degree chiziqlar","Qiya devorlar","Polar incrementni sozlang."),
"SNAP":("F9","Cursorni grid intervaliga bog'laydi.","F9","10 mm qadam bilan chizish","Modulli plan","OSNAP bilan aralashtirmang."),
"GRID":("F7","Gridni ko'rsatadi/yashiradi.","F7","Chizma gridini ko'rish","Drafting","Grid spacingni sozlang."),
"DYNMODE":("F12","Dynamic Inputni yoqadi/o'chiradi.","F12","Cursor yonida masofa/burchak","Tez chizish","Coordinate input bilan juda qulay."),
"DUCS":("F6","Dynamic UCSni boshqaradi.","F6","3D yuzaga mos UCS","3D model","Asosan 3D workflow."),
"UCSFOLLOW":("—","UCS o'zgarganda viewni unga moslaydi.","UCSFOLLOW -> 1","Qiya UCS bilan ishlash","Qiya plan/detal","Keraksiz view rotationdan ehtiyot bo'ling."),
"PICKFIRST":("—","Commanddan oldin obyekt tanlashni boshqaradi.","PICKFIRST -> 1","Avval obyekt tanlab keyin ERASE","Workflow","Odatda 1 bo'lib turadi."),
"PICKADD":("—","Selectionga obyekt qo'shishni boshqaradi.","PICKADD -> 2","Bir nechta obyekt tanlash","Selection","Selection behavior o'zgarishi mumkin."),
"PICKSTYLE":("—","Group va associative hatch selectionini boshqaradi.","PICKSTYLE","Group selection","Plan va hatch","Group bilan ishlaganda muhim."),
"FILEDIA":("—","Dialog oynalarini yoqadi/o'chiradi.","FILEDIA -> 1","Open/Save dialog","Fayl boshqaruvi","0 bo'lsa command line workflow ishlashi mumkin."),
"PICKBOX":("—","Selection pickbox o'lchamini boshqaradi.","PICKBOX -> value","Selection cursorini kattalashtirish","Aniq tanlash","Juda katta qiymat noqulay."),
"SELECTIONCYCLING":("—","Ustma-ust obyektlardan tanlashni boshqaradi.","SELECTIONCYCLING","Bir nechta ustma-ust chiziq","Murakkab DWG","2 holati selectionni osonlashtiradi."),
"SELECTIONPREVIEW":("—","Cursor ustidagi selection previewni boshqaradi.","SELECTIONPREVIEW","Hover paytida obyekt highlight","Tez tanlash","Katta DWGda performancega ta'sir qilishi mumkin."),

"PLOT":("CTRL+P","Chizmani printer/PDFga chiqaradi.","PLOT -> printer -> paper -> scale","A3 PDF 1:100","Sheet chiqarish","Previewni har doim tekshiring."),
"PREVIEW":("—","Plotdan oldin natijani ko'rsatadi.","PREVIEW","PDFdan oldin tekshirish","Chop etish","Lineweight va clippingni tekshiring."),
"PAGESETUP":("—","Layout plot sozlamalarini saqlaydi.","PAGESETUP -> layout","A1 PDF setup","Sheet standardlari","Template bilan saqlash qulay."),
"PUBLISH":("PUBLISH","Bir nechta sheetni birgalikda chiqaradi.","PUBLISH -> sheets","10 ta A3 sheetni PDF qilish","Katta loyiha topshirig'i","Named Page Setup ishlating."),
"EXPORTPDF":("EXPORTPDF","DWGni PDFga eksport qiladi.","EXPORTPDF","Plan.pdf yaratish","Taqdimot va topshirish","Layer information kerak bo'lsa sozlang."),
"EXPORT":("EXPORT","Chizmani boshqa formatga eksport qiladi.","EXPORT -> format","DXF/SVG va boshqa formatlar","Fayl almashinuvi","Format variantlarini tekshiring."),

"BOX":("BOX","3D box solid yaratadi.","BOX -> corner -> dimensions","6000x3000x3000","3D bino massasi","3D modeling."),
"CYLINDER":("CYL","3D silindr yaratadi.","CYL -> center -> radius -> height","D300 x 3000","Ustunlar","Solid yaratish uchun qulay."),
"CONE":("CONE","3D konus yaratadi.","CONE -> center -> radius -> height","Radiusli tom elementi","3D arxitektura","Top radius orqali frustum qilish mumkin."),
"SPHERE":("SPH","3D sfera yaratadi.","SPH -> center -> radius","R1000 sphere","Dekor va massa","3D visualization."),
"TORUS":("TOR","Halqasimon 3D solid yaratadi.","TOR -> center -> radii","Torus detal","Dekorativ elementlar","Major/minor radiusni ajrating."),
"WEDGE":("WE","3D pona yaratadi.","WEDGE -> corner -> dimensions","Ramp element","3D detal","Directionga e'tibor bering."),
"PYRAMID":("PYR","3D piramida yaratadi.","PYR -> sides -> center -> radius -> height","5-sided massa","Arxitektura formasi","Base type va radiusni tanlang."),
"REVOLVE":("REV","2D profilni o'q atrofida aylantirib 3D solid/surface yaratadi.","REV -> profile -> axis -> angle","Ustun profilini 360 degree aylantirish","3D arxitektura","Profil yopiq bo'lsa solid yaratish mumkin."),
"EXTRUDE":("EXT","2D profilni balandlik bo'yicha 3Dga chiqaradi.","EXT -> profile -> height","6000x3000 profil -> 3000","Devor va massa model","Closed profile solid uchun qulay."),
"SWEEP":("SW","Profilni path bo'ylab olib boradi.","SW -> profile -> path","Profilni egri yo'l bo'ylab sweep","Bionik fasad va railing","Twist/scale variantlarini tekshiring."),
"LOFT":("LO","Bir nechta kesim orasida 3D forma yaratadi.","LO -> cross sections","Turli sectionlardan forma","Murakkab arxitektura massasi","Guides va path ishlatilishi mumkin."),
"PRESSPULL":("PRESSPULL","Yopiq maydonni push/pull qiladi.","PRESSPULL -> area -> distance","Xonani 3D hajmga chiqarish","Tez 3D modeling","Face yoki closed area tanlang."),
"UNION":("UNI","3D solidlarni birlashtiradi.","UNI -> solids","Ikki massa -> bitta solid","Bino massasi","Faqat mos solid/surface turlari bilan ishlaydi."),
"SUBTRACT":("SU","Bir solidni boshqasidan ayiradi.","SU -> main -> cutting solid","Deraza teshigini boolean bilan ochish","3D bino modeli","Avval main solid, keyin cutter tanlanadi."),
"INTERSECT":("IN","Solidlarning kesishgan qismini qoldiradi.","IN -> solids","Ikki massaning umumiy qismi","Murakkab 3D geometriya","Original solidlar yo'qoladi."),
"SLICE":("SL","Solidni tekislik bilan kesadi.","SL -> solid -> plane","Binoni kesib ko'rish","3D section","Keep both sides variantini biling."),
"THICKEN":("TH","Surfacega qalinlik beradi.","TH -> surface -> thickness","Fasad surfaceiga 100 mm qalinlik","3D fasad","Positive/negative directionni tekshiring."),
"SOLIDEDIT":("SOLIDEDIT","3D solidlarni tahrirlaydi.","SOLIDEDIT -> face/body","Face offset yoki shell","3D arxitektura","Subcommandlar ko'p."),

"FILLETEDGE":("FILLETEDGE","3D solid qirrasiga radius beradi.","FILLETEDGE -> edge -> radius","R100 qirra","3D fasad va mebel","Preview bilan tekshiring."),
"CHAMFEREDGE":("CHAMFEREDGE","3D solid qirrasini qirqadi.","CHAMFEREDGE -> edge -> distances","50 mm chamfer","3D detal","Distance direction muhim."),
"CONVTOSOLID":("CONVTOSOLID","Mos surface/mesh/closed geometryni solidga aylantirishga urinadi.","CONVTOSOLID -> object","Closed surface -> solid","3D modeling","Geometriya yopiq bo'lishi kerak."),
"CONVTOSURFACE":("CONVTOSURFACE","Obyektni surfacega aylantiradi.","CONVTOSURFACE -> object","3D face/solid -> surface","Erkin shaklli fasad","Object turiga bog'liq."),
"CONVTOMESH":("CONVTOMESH","Obyektni meshga aylantiradi.","CONVTOMESH -> object","Solid -> mesh","Conceptual 3D","Mesh resolution sozlamalarini hisobga oling."),
"CONVERTPOLY":("CONVERTPOLY","Polyline turini boshqa polyline turiga o'tkazadi.","CONVERTPOLY -> object","3D polyline conversion","Geometriya workflow","2D/3D polyline turini tekshiring.")
}

AUTOCAD_COMMANDS = {}

for name, data in COMMANDS.items():
    shortcut, purpose, usage, example, architecture, tip = data
    AUTOCAD_COMMANDS[name] = {
        "shortcut": shortcut,
        "vazifasi": purpose,
        "ishlatish": usage,
        "misol": example,
        "arxitektura": architecture,
        "maslahat": tip
    }

with open("autocad_commands.py", "w", encoding="utf-8") as f:
    f.write("AUTOCAD_COMMANDS = ")
    f.write(repr(AUTOCAD_COMMANDS))
    f.write("\n")
    f.write("\n# Professional AutoCAD command base\n")
    f.write("# Total commands: " + str(len(AUTOCAD_COMMANDS)) + "\n")
